services:
  redis:
    image: redis:7
    container_name: bms-redis
    restart: unless-stopped

  bot:
    image: bms-rev1:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bms-bot
    restart: unless-stopped
    env_file: .env
    environment:
      TZ: Asia/Kolkata
      BMS_FORCE_UC: "1"
      REDIS_URL: redis://redis:6379/0
    volumes:
      - /var/lib/bms/artifacts:/app/artifacts
    shm_size: "1g"
    command: python -m bot.bot
    depends_on:
      - redis

  worker:
    image: bms-rev1:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bms-worker
    restart: unless-stopped
    env_file: .env
    environment:
      TZ: Asia/Kolkata
      BMS_FORCE_UC: "1"
      REDIS_URL: redis://redis:6379/0
    volumes:
      - /var/lib/bms/artifacts:/app/artifacts
    shm_size: "1g"
    command: python -m worker
    depends_on:
      - redis
