name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: pip install black flake8 mypy pytest pytest-cov
      - run: black --check common.py utils.py store.py tests
      - run: flake8 common.py utils.py store.py tests
      - run: mypy common.py utils.py store.py scraper.py
      - run: pytest
